### ISSUE TITLE
Failed to inject hook 6

### ISSUE THREAD

**Issue by Madsp1ke** [Krappa322/arcdps_unofficial_extras_releases#27]
![image](https://github.com/user-attachments/assets/fa5250ff-a85e-4441-bb2f-405180f90fe0)

**Comment by Krappa322** [comment]
Thanks for reporting!

The auto update feature broke in 1.19 due to a bug in the http library we use. You have to manually download the newest version at https://github.com/Krappa322/arcdps_unofficial_extras_releases/releases/latest (or, since it looks like you're using nexus, use it to perform the update). That should fix the hook injection issue.

**Comment by Madsp1ke** [comment]
Since Nexus didn't have update button for this addon, i manually downloaded the .dll from the link you provided. 
It worked. Many thanks <3

**Comment by C0WAL** [comment]
Hi, I have downloaded the newest possible unofficial extras from https://github.com/Krappa322/arcdps_unofficial_extras_releases/releases/latest but I still get 
![image](https://github.com/user-attachments/assets/f67c60cd-ad6f-4cf9-84e2-29242a8bef95)
